/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfDiscoveryRouteImport } from './routes/self-discovery'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as MyHealthPassportRouteImport } from './routes/my-health-passport'
import { Route as FindProviderRouteImport } from './routes/find-provider'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharePreviewRouteImport } from './routes/share.preview'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SelfDiscoverySlugRouteImport } from './routes/self-discovery_.$slug'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SelfDiscoveryRoute = SelfDiscoveryRouteImport.update({
  id: '/self-discovery',
  path: '/self-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHealthPassportRoute = MyHealthPassportRouteImport.update({
  id: '/my-health-passport',
  path: '/my-health-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const FindProviderRoute = FindProviderRouteImport.update({
  id: '/find-provider',
  path: '/find-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePreviewRoute = SharePreviewRouteImport.update({
  id: '/share/preview',
  path: '/share/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfDiscoverySlugRoute = SelfDiscoverySlugRouteImport.update({
  id: '/self-discovery_/$slug',
  path: '/self-discovery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/api/chat': typeof ApiChatRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/api/chat': typeof ApiChatRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/api/chat': typeof ApiChatRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery_/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/resources'
    | '/self-discovery'
    | '/api/chat'
    | '/provider/$id'
    | '/self-discovery/$slug'
    | '/share/$token'
    | '/share/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/resources'
    | '/self-discovery'
    | '/api/chat'
    | '/provider/$id'
    | '/self-discovery/$slug'
    | '/share/$token'
    | '/share/preview'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/resources'
    | '/self-discovery'
    | '/api/chat'
    | '/provider/$id'
    | '/self-discovery_/$slug'
    | '/share/$token'
    | '/share/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  CheckoutRoute: typeof CheckoutRoute
  FindProviderRoute: typeof FindProviderRoute
  MyHealthPassportRoute: typeof MyHealthPassportRoute
  ResourcesRoute: typeof ResourcesRoute
  SelfDiscoveryRoute: typeof SelfDiscoveryRoute
  ApiChatRoute: typeof ApiChatRoute
  ProviderIdRoute: typeof ProviderIdRoute
  SelfDiscoverySlugRoute: typeof SelfDiscoverySlugRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SharePreviewRoute: typeof SharePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-discovery': {
      id: '/self-discovery'
      path: '/self-discovery'
      fullPath: '/self-discovery'
      preLoaderRoute: typeof SelfDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-health-passport': {
      id: '/my-health-passport'
      path: '/my-health-passport'
      fullPath: '/my-health-passport'
      preLoaderRoute: typeof MyHealthPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-provider': {
      id: '/find-provider'
      path: '/find-provider'
      fullPath: '/find-provider'
      preLoaderRoute: typeof FindProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/preview': {
      id: '/share/preview'
      path: '/share/preview'
      fullPath: '/share/preview'
      preLoaderRoute: typeof SharePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-discovery_/$slug': {
      id: '/self-discovery_/$slug'
      path: '/self-discovery/$slug'
      fullPath: '/self-discovery/$slug'
      preLoaderRoute: typeof SelfDiscoverySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  CheckoutRoute: CheckoutRoute,
  FindProviderRoute: FindProviderRoute,
  MyHealthPassportRoute: MyHealthPassportRoute,
  ResourcesRoute: ResourcesRoute,
  SelfDiscoveryRoute: SelfDiscoveryRoute,
  ApiChatRoute: ApiChatRoute,
  ProviderIdRoute: ProviderIdRoute,
  SelfDiscoverySlugRoute: SelfDiscoverySlugRoute,
  ShareTokenRoute: ShareTokenRoute,
  SharePreviewRoute: SharePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
