/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SelfDiscoveryRouteImport } from './routes/self-discovery'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProviderOnboardingRouteImport } from './routes/provider-onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as MyHealthPassportRouteImport } from './routes/my-health-passport'
import { Route as FindProviderRouteImport } from './routes/find-provider'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharePreviewRouteImport } from './routes/share.preview'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as SelfDiscoverySlugRouteImport } from './routes/self-discovery_.$slug'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProfilePreviewRouteImport } from './routes/profile.preview'
import { Route as AppointmentRescheduleRouteImport } from './routes/appointment.reschedule'
import { Route as AppointmentDetailsRouteImport } from './routes/appointment.details'
import { Route as AppointmentCancelRouteImport } from './routes/appointment.cancel'
import { Route as ApiEnhanceProfileRouteImport } from './routes/api/enhance-profile'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfDiscoveryRoute = SelfDiscoveryRouteImport.update({
  id: '/self-discovery',
  path: '/self-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/provider-onboarding',
  path: '/provider-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHealthPassportRoute = MyHealthPassportRouteImport.update({
  id: '/my-health-passport',
  path: '/my-health-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const FindProviderRoute = FindProviderRouteImport.update({
  id: '/find-provider',
  path: '/find-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePreviewRoute = SharePreviewRouteImport.update({
  id: '/share/preview',
  path: '/share/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfDiscoverySlugRoute = SelfDiscoverySlugRouteImport.update({
  id: '/self-discovery_/$slug',
  path: '/self-discovery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePreviewRoute = ProfilePreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProfileRoute,
} as any)
const AppointmentRescheduleRoute = AppointmentRescheduleRouteImport.update({
  id: '/appointment/reschedule',
  path: '/appointment/reschedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentDetailsRoute = AppointmentDetailsRouteImport.update({
  id: '/appointment/details',
  path: '/appointment/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentCancelRoute = AppointmentCancelRouteImport.update({
  id: '/appointment/cancel',
  path: '/appointment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhanceProfileRoute = ApiEnhanceProfileRouteImport.update({
  id: '/api/enhance-profile',
  path: '/api/enhance-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider-onboarding': typeof ProviderOnboardingRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enhance-profile': typeof ApiEnhanceProfileRoute
  '/appointment/cancel': typeof AppointmentCancelRoute
  '/appointment/details': typeof AppointmentDetailsRoute
  '/appointment/reschedule': typeof AppointmentRescheduleRoute
  '/profile/preview': typeof ProfilePreviewRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider-onboarding': typeof ProviderOnboardingRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enhance-profile': typeof ApiEnhanceProfileRoute
  '/appointment/cancel': typeof AppointmentCancelRoute
  '/appointment/details': typeof AppointmentDetailsRoute
  '/appointment/reschedule': typeof AppointmentRescheduleRoute
  '/profile/preview': typeof ProfilePreviewRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/checkout': typeof CheckoutRoute
  '/find-provider': typeof FindProviderRoute
  '/my-health-passport': typeof MyHealthPassportRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/provider-onboarding': typeof ProviderOnboardingRoute
  '/resources': typeof ResourcesRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enhance-profile': typeof ApiEnhanceProfileRoute
  '/appointment/cancel': typeof AppointmentCancelRoute
  '/appointment/details': typeof AppointmentDetailsRoute
  '/appointment/reschedule': typeof AppointmentRescheduleRoute
  '/profile/preview': typeof ProfilePreviewRoute
  '/provider/$id': typeof ProviderIdRoute
  '/self-discovery_/$slug': typeof SelfDiscoverySlugRoute
  '/share/$token': typeof ShareTokenRoute
  '/share/preview': typeof SharePreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/profile'
    | '/provider-onboarding'
    | '/resources'
    | '/self-discovery'
    | '/terms'
    | '/api/chat'
    | '/api/enhance-profile'
    | '/appointment/cancel'
    | '/appointment/details'
    | '/appointment/reschedule'
    | '/profile/preview'
    | '/provider/$id'
    | '/self-discovery/$slug'
    | '/share/$token'
    | '/share/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/profile'
    | '/provider-onboarding'
    | '/resources'
    | '/self-discovery'
    | '/terms'
    | '/api/chat'
    | '/api/enhance-profile'
    | '/appointment/cancel'
    | '/appointment/details'
    | '/appointment/reschedule'
    | '/profile/preview'
    | '/provider/$id'
    | '/self-discovery/$slug'
    | '/share/$token'
    | '/share/preview'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/check-in'
    | '/checkout'
    | '/find-provider'
    | '/my-health-passport'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/profile'
    | '/provider-onboarding'
    | '/resources'
    | '/self-discovery'
    | '/terms'
    | '/api/chat'
    | '/api/enhance-profile'
    | '/appointment/cancel'
    | '/appointment/details'
    | '/appointment/reschedule'
    | '/profile/preview'
    | '/provider/$id'
    | '/self-discovery_/$slug'
    | '/share/$token'
    | '/share/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  CheckoutRoute: typeof CheckoutRoute
  FindProviderRoute: typeof FindProviderRoute
  MyHealthPassportRoute: typeof MyHealthPassportRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
  ResourcesRoute: typeof ResourcesRoute
  SelfDiscoveryRoute: typeof SelfDiscoveryRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEnhanceProfileRoute: typeof ApiEnhanceProfileRoute
  AppointmentCancelRoute: typeof AppointmentCancelRoute
  AppointmentDetailsRoute: typeof AppointmentDetailsRoute
  AppointmentRescheduleRoute: typeof AppointmentRescheduleRoute
  ProviderIdRoute: typeof ProviderIdRoute
  SelfDiscoverySlugRoute: typeof SelfDiscoverySlugRoute
  ShareTokenRoute: typeof ShareTokenRoute
  SharePreviewRoute: typeof SharePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-discovery': {
      id: '/self-discovery'
      path: '/self-discovery'
      fullPath: '/self-discovery'
      preLoaderRoute: typeof SelfDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-onboarding': {
      id: '/provider-onboarding'
      path: '/provider-onboarding'
      fullPath: '/provider-onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-health-passport': {
      id: '/my-health-passport'
      path: '/my-health-passport'
      fullPath: '/my-health-passport'
      preLoaderRoute: typeof MyHealthPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-provider': {
      id: '/find-provider'
      path: '/find-provider'
      fullPath: '/find-provider'
      preLoaderRoute: typeof FindProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/preview': {
      id: '/share/preview'
      path: '/share/preview'
      fullPath: '/share/preview'
      preLoaderRoute: typeof SharePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-discovery_/$slug': {
      id: '/self-discovery_/$slug'
      path: '/self-discovery/$slug'
      fullPath: '/self-discovery/$slug'
      preLoaderRoute: typeof SelfDiscoverySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/preview': {
      id: '/profile/preview'
      path: '/preview'
      fullPath: '/profile/preview'
      preLoaderRoute: typeof ProfilePreviewRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/appointment/reschedule': {
      id: '/appointment/reschedule'
      path: '/appointment/reschedule'
      fullPath: '/appointment/reschedule'
      preLoaderRoute: typeof AppointmentRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment/details': {
      id: '/appointment/details'
      path: '/appointment/details'
      fullPath: '/appointment/details'
      preLoaderRoute: typeof AppointmentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment/cancel': {
      id: '/appointment/cancel'
      path: '/appointment/cancel'
      fullPath: '/appointment/cancel'
      preLoaderRoute: typeof AppointmentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-profile': {
      id: '/api/enhance-profile'
      path: '/api/enhance-profile'
      fullPath: '/api/enhance-profile'
      preLoaderRoute: typeof ApiEnhanceProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfilePreviewRoute: typeof ProfilePreviewRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePreviewRoute: ProfilePreviewRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  CheckoutRoute: CheckoutRoute,
  FindProviderRoute: FindProviderRoute,
  MyHealthPassportRoute: MyHealthPassportRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
  ResourcesRoute: ResourcesRoute,
  SelfDiscoveryRoute: SelfDiscoveryRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEnhanceProfileRoute: ApiEnhanceProfileRoute,
  AppointmentCancelRoute: AppointmentCancelRoute,
  AppointmentDetailsRoute: AppointmentDetailsRoute,
  AppointmentRescheduleRoute: AppointmentRescheduleRoute,
  ProviderIdRoute: ProviderIdRoute,
  SelfDiscoverySlugRoute: SelfDiscoverySlugRoute,
  ShareTokenRoute: ShareTokenRoute,
  SharePreviewRoute: SharePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
