drop table if exists public.ai_suggestion_runs cascade;
drop table if exists public.prescription_delivery_events cascade;
drop table if exists public.prescription_audit_events cascade;
drop table if exists public.signature_events cascade;
drop table if exists public.signing_challenges cascade;
drop table if exists public.signed_prescription_versions cascade;
drop table if exists public.prescription_safety_findings cascade;
drop table if exists public.prescription_safety_reviews cascade;
drop table if exists public.prescription_items cascade;
drop table if exists public.prescription_drafts cascade;
drop table if exists public.clinical_notes cascade;
drop table if exists public.assessments cascade;
drop table if exists public.patient_allergies cascade;
drop table if exists public.patient_conditions cascade;
drop table if exists public.patient_medications cascade;
drop table if exists public.patient_observations_labs cascade;
drop table if exists public.encounters cascade;
drop table if exists public.appointments cascade;
drop table if exists public.medication_sources cascade;
drop table if exists public.medication_products_ph cascade;
drop table if exists public.medication_concepts cascade;
drop table if exists public.provider_verifications cascade;
drop table if exists public.provider_authorities cascade;
drop table if exists public.provider_profiles cascade;
drop table if exists public.profiles cascade;
drop table if exists public.user_roles cascade;

drop function if exists public.can_prescribe_ph(uuid, uuid) cascade;
drop function if exists public.has_role(uuid, public.app_role) cascade;
drop function if exists public.is_draft_provider(uuid) cascade;
drop function if exists public.is_encounter_patient(uuid) cascade;
drop function if exists public.is_encounter_provider(uuid) cascade;
drop function if exists public.protect_signature_events() cascade;
drop function if exists public.protect_signed_prescription() cascade;
drop function if exists public.set_updated_at() cascade;

drop type if exists public.app_role cascade;
drop type if exists public.catalog_approval cascade;
drop type if exists public.clinical_state cascade;
drop type if exists public.finding_severity cascade;
drop type if exists public.jurisdiction_code cascade;
drop type if exists public.rx_draft_status cascade;
drop type if exists public.verification_status cascade;